### ISSUE TITLE
[Question] Breaking after adding firebase?

### ISSUE THREAD

**Issue by scheung38** [meedu-app/flutter-facebook-login-example#1]
Cloned this app, and it works and redirects me to facebook login and returns back to app as expected, but as soon as I add 

firebase_core 

cd ios && pod update

it breaks?

pubspec.yaml:

```
name: facebook_auth_example
description: A new Flutter project.
 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_facebook_auth: ^2.0.1
  change_app_package_name: ^0.1.2

  # firebase_core: ^0.7.0 <-- breaks after adding this?

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:

  uses-material-design: true
```

EDIT: Seems to work again after flutter build -t lib/main.dart
